version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
        auth: 
          username: corbravo
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: v2-dependencies-{{ checksum "requirements.txt" }}
      - run: 
          command: pip install -r requirements.txt
      - save_cache:
          key: v2-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "~/.cache/pip"
            - "/usr/local/lib/python3.8/site-packages"
            - "/usr/local/lib/site-python"
      - run:
          name: Run tests
          command: | 
           python manage.py test
      - run: 
          name: Linting
          command: flake8
  containerization:
    docker:
      - image: circleci/python:3.8
        auth:
         username: corbravo
         password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: create-image
          command: | 
            echo $DOCKERHUB_PASSWORD | docker login --username corbravo --password-stdin
            docker build -t oc-lettings .
            docker tag oc-lettings corbravo/oc-lettings:$CIRCLE_SHA1 
            docker image push corbravo/oc-lettings:$CIRCLE_SHA1
  deploy:
    docker:
      - image: circleci/python:3.8
        auth:
            username: corbravo
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
        # To be done
          name: do-nothing
          command:
            echo $DOCKERHUB_PASSWORD | docker login --username corbravo --password-stdin
    
      


workflows:
  sample:
    jobs:
      - build-and-test
      - containerization:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - containerization
          filters:
            branches:
              only: master
