version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8
        auth: 
          username: corbravo
          password: $DOCKERHUB_PASSWORD
    environment:
      DJANGO_KEY: ${django_key}
      ENV: ${env}
    steps:
      - checkout
      - restore_cache:
          key: v3-dependencies-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: v3-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: | 
           . venv/bin/activate
           python manage.py test --noinput

      - run: 
          name: Linting
          command: |
            . venv/bin/activate
            flake8
  containerization:
    docker:
      - image: circleci/python:3.8
        auth:
         username: corbravo
         password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: create-image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username corbravo --password-stdin
            docker build -t oc-lettings --build-arg django_key=${django_key} --build-arg env=${env} .
            docker tag oc-lettings corbravo/oc-lettings:$CIRCLE_SHA1
            docker tag oc-lettings corbravo/oc-lettings:latest
            docker image push corbravo/oc-lettings:$CIRCLE_SHA1
            docker image push corbravo/oc-lettings:latest



workflows:
  sample:
    jobs:
      - build-and-test
      - containerization:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - heroku/deploy-via-git:
          requires:
            - containerization
          filters:
            branches:
              only: master
          post-steps:
            - run:
                command: heroku run -a oc-lettings-cbravo python manage.py migrate
